### PR TITLE
Fix for `consider-using-f-string`

### PR DESCRIPTION
**Pull request by Ruchip16**
Wherever the .format() method was being used, replaced with an f-string.

CC: @ssbarnea @cidrblock

### CODE REVIEW

**Comment by priyamsahoo** [comment]
These contain both changes. That is, it includes the changes from #88 as well. You might have to cherry-pick and remove them.

**Comment by Ruchip16** [comment]
> These contain both changes. That is, it includes the changes from #88 as well. You might have to cherry-pick and remove them.

yes both commits were pushed into this and now when i would push changes again i think in #88 the f-string changes would also get pushed again as the commit is visible in git log so should i remove that commit before pushing anything or should i keep it as the f-string ones are just simple string changes and anyway it needed to be fix later?

**Comment by priyamsahoo** [comment]
> > These contain both changes. That is, it includes the changes from #88 as well. You might have to cherry-pick and remove them.
> 
> yes since this branch was checked out from the previous PR branch both commits were pushed into this and now when i would push changes again i think in #88 the f-string changes would also get pushed again as the commit is visible in git log so should i remove that commit before pushing anything or should i keep it as the f-string ones are just simple string changes and anyway it needs to be addressed later?

Tip: Do a soft reset till the first f-string commit. Stash the changes. Checkout to a new branch from the main branch, and apply the stash over there. in this way, you can separate out the changes.

**Comment by Ruchip16** [comment]
closing this PR, since #90 has been raised for the same

**Pull request closed without merging**
